// Code generated by goctl. DO NOT EDIT.
package types

type Illust struct {
	Title      string `json:"title"`       // 画集的名称
	IllustID   int64  `json:"illust_id"`   // 画集的ID
	ThumbURL   string `json:"thumb_url"`   // 缩略图URL
	UserName   string `json:"user_name"`   // 用户名称
	ProfileImg string `json:"profile_img"` // 用户头像的URL
	Rank       int    `json:"rank"`        // 相似度的排名
}

type ImageResp struct {
	Error     string   `json:"error"`      // 如果没有错误为null,如果有错误则为错误信息
	ErrorCode int      `json:"error_code"` // 业务码
	Contents  []Illust `json:"contents"`   // 列表，类型为 Illust
	Tags      []string `json:"tags"`       // 标签列表，类型为 string
}
