// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	imagePredction "web-app/internal/handler/imagePredction"
	"web-app/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MD5Check, serverCtx.TypeCheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/predict",
					Handler: imagePredction.PredictHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
		rest.WithMaxBytes(5242880),
		rest.WithTimeout(30 * time.Second),
	)
}
