CREATE TABLE `pixiv_illust` (
  `illust_id` int(11) NOT NULL COMMENT '作品ID',
  `illust_title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '作品标题',
  `illust_comment` text COLLATE utf8mb4_unicode_ci COMMENT '作品评论',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '作品描述',
  `illust_type` int(11) DEFAULT NULL COMMENT '作品类型',
  `create_date` datetime DEFAULT NULL COMMENT '作品创建日期',
  `upload_date` datetime DEFAULT NULL COMMENT '作品上传日期',
  `restrict` int(11) DEFAULT NULL COMMENT '作品限制',
  `x_restrict` int(11) DEFAULT NULL COMMENT '作品X限制',
  `sl` int(11) DEFAULT NULL COMMENT '作品SL',
  `mini_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '缩略图URL',
  `thumb_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '缩略图URL',
  `small_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '小图URL',
  `regular_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '普通图URL',
  `original_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '原图URL',
  `alt` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '作品ALT',
  `user_id` int(11) DEFAULT NULL COMMENT '用户ID',
  `user_name` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户名称',
  `user_account` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户账号',
  `width` int(11) DEFAULT NULL COMMENT '作品宽度',
  `height` int(11) DEFAULT NULL COMMENT '作品高度',
  `page_count` int(11) DEFAULT NULL COMMENT '作品页数',
  `bookmark_count` int(11) DEFAULT NULL COMMENT '作品收藏数',
  `like_count` int(11) DEFAULT NULL COMMENT '作品点赞数',
  `comment_count` int(11) DEFAULT NULL COMMENT '作品评论数',
  `response_count` int(11) DEFAULT NULL COMMENT '作品回复数',
  `view_count` int(11) DEFAULT NULL COMMENT '作品浏览数',
  `book_style` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '作品书籍风格',
  `is_howto` tinyint(1) DEFAULT NULL COMMENT '是否为教程',
  `is_original` tinyint(1) DEFAULT NULL COMMENT '是否为原创',
  `last_update` datetime DEFAULT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`illust_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Pixiv作品集数据表';